"""Domain operations, with Planbook's abbreviated field names translated.

The wire format uses keys like `cId`, `cN`, `mSt`, so everything leaving this
module is renamed. `--raw` bypasses the translation when you need to see
exactly what the server said.
"""

from __future__ import annotations

from .resources.classes import (
    class_payload,
    create_class,
    delete_class,
    get_class,
    list_classes,
    normalize_class,
    update_class,
)
from .resources.events import (
    EVENT_SCHEDULES,
    EVENT_TYPES,
    create_event,
    delete_event,
    event_payload,
    find_event,
    list_events,
    new_event_payload,
)
from .resources.lessons import (
    DEFAULT_SECTION_LABELS,
    SECTION_FIELDS,
    _as_date,
    delete_lesson,
    find_lesson,
    get_week,
    iter_days,
    lesson_payload,
    lesson_sections,
    lessons_between,
    no_school_dates,
    read_week,
    resolve_section,
    set_lesson,
)
from .resources.misc import (
    SIMPLE_READS,
    attachments,
    list_assignments,
    list_attachments,
    resolve_attachment,
    settings,
    simple_read,
    special_days,
    standards,
    upload_attachment,
)
from .resources.people import (
    create_student,
    delete_student,
    get_attendance,
    get_scores,
    list_students,
    list_templates,
    student_payload,
    update_student,
)
from .resources.todos import (
    TODO_PRIORITIES,
    _todo_payload,
    create_todo,
    delete_todo,
    list_todos,
    update_todo,
)
from .resources.units import (
    UNIT_ACTIONS,
    create_unit,
    delete_unit,
    list_units,
    unit_payload,
    update_unit,
)
from .wire import (
    DAY_LETTERS,
    DAY_ORDER,
    DAY_PREFIXES,
    SCHEDULE_DAY_ORDER,
    SCHEDULE_SLOTS,
    TIME_RE,
    Payload,
    build_schedule,
    edit_schedule,
    intish,
    parse_date,
    parse_day_times,
    parse_days,
    parse_time,
    yn,
)

__all__ = [
    "DAY_LETTERS",
    "DAY_ORDER",
    "DAY_PREFIXES",
    "DEFAULT_SECTION_LABELS",
    "EVENT_SCHEDULES",
    "EVENT_TYPES",
    "SCHEDULE_DAY_ORDER",
    "SCHEDULE_SLOTS",
    "SECTION_FIELDS",
    "SIMPLE_READS",
    "TIME_RE",
    "TODO_PRIORITIES",
    "UNIT_ACTIONS",
    "Payload",
    "_as_date",
    "_todo_payload",
    "attachments",
    "build_schedule",
    "class_payload",
    "create_class",
    "create_event",
    "create_student",
    "create_todo",
    "create_unit",
    "delete_class",
    "delete_event",
    "delete_lesson",
    "delete_student",
    "delete_todo",
    "delete_unit",
    "edit_schedule",
    "event_payload",
    "find_event",
    "find_lesson",
    "get_attendance",
    "get_class",
    "get_scores",
    "get_week",
    "intish",
    "iter_days",
    "lesson_payload",
    "lesson_sections",
    "lessons_between",
    "list_assignments",
    "list_attachments",
    "list_classes",
    "list_events",
    "list_students",
    "list_templates",
    "list_todos",
    "list_units",
    "new_event_payload",
    "no_school_dates",
    "normalize_class",
    "parse_date",
    "parse_day_times",
    "parse_days",
    "parse_time",
    "read_week",
    "resolve_attachment",
    "resolve_section",
    "set_lesson",
    "settings",
    "simple_read",
    "special_days",
    "standards",
    "student_payload",
    "unit_payload",
    "update_class",
    "update_student",
    "update_todo",
    "update_unit",
    "upload_attachment",
    "yn",
]
